function outputFiles = assemble_supplementary_figures(outputDir)
%ASSEMBLE_SUPPLEMENTARY_FIGURES Build publication and cmocean matrices.
%   ASSEMBLE_SUPPLEMENTARY_FIGURES reads the PNG panels generated by the
%   four temporal Live Scripts from data/temporal/. It writes both the
%   original jet-colour compositions and perceptually uniform cmocean
%   alternatives to figures/.
%
%   OUTPUTFILES = ASSEMBLE_SUPPLEMENTARY_FIGURES(OUTPUTDIR) writes the
%   matrices to a custom directory and returns their paths.
%
%   Run the four Live Scripts before calling this function:
%     station3_ctd.mlx
%     station6_ctd.mlx
%     station3_nutrients.mlx
%     station6_nutrients.mlx

scriptDir = fileparts(mfilename('fullpath'));
repoRoot = fileparts(fileparts(scriptDir));
inputDir = fullfile(repoRoot, 'data', 'temporal');
thirdPartyDir = fullfile(repoRoot, 'third_party');
addpath(thirdPartyDir);

if nargin < 1 || isempty(outputDir)
    outputDir = fullfile(repoRoot, 'figures');
end

if ~isfolder(inputDir)
    error('Panel input directory not found: %s', inputDir);
end
if ~isfolder(outputDir)
    mkdir(outputDir);
end

columns = struct( ...
    'season', {'Winter', 'Spring', 'Summer', 'Winter', 'Spring', 'Summer'}, ...
    'station', {'S3', 'S3', 'S3', 'S6', 'S6', 'S6'});

ctdVariables = {'Temp', 'Fluo', 'Par', 'Sal', 'Turb'};
ctdLabels = { ...
    'Temperature (^{\circ}C)', ...
    'Chl-a (\mug L^{-1})', ...
    'PAR (\mumol photons m^{-2} s^{-1})', ...
    'Salinity (PSU)', ...
    'Turbidity (NTU)'};
ctdPalettes = {'thermal', 'algae', 'solar', 'haline', 'turbid'};

nutrientVariables = {'NH4', 'NO2', 'NO3', 'SiO2', 'PO4'};
nutrientLabels = { ...
    'NH_{4}^{+} (\mumol L^{-1})', ...
    'NO_{2}^{-} (\mumol L^{-1})', ...
    'NO_{3}^{-} (\mumol L^{-1})', ...
    'SiO_{2} (\mumol L^{-1})', ...
    'PO_{4}^{3-} (\mumol L^{-1})'};
nutrientPalettes = repmat({'matter'}, size(nutrientVariables));

outputFiles = { ...
    fullfile(outputDir, 'supplementary_figure_1.png'), ...
    fullfile(outputDir, 'supplementary_figure_2.png'), ...
    fullfile(outputDir, 'supplementary_figure_1_cmocean.png'), ...
    fullfile(outputDir, 'supplementary_figure_2_cmocean.png')};

buildMatrix(inputDir, outputFiles{1}, columns, ctdVariables, ctdLabels, ...
    'ctd', 'original', ctdPalettes);
buildMatrix(inputDir, outputFiles{2}, columns, nutrientVariables, ...
    nutrientLabels, 'nutrients', 'original', nutrientPalettes);
buildMatrix(inputDir, outputFiles{3}, columns, ctdVariables, ctdLabels, ...
    'ctd', 'cmocean', ctdPalettes);
buildMatrix(inputDir, outputFiles{4}, columns, nutrientVariables, ...
    nutrientLabels, 'nutrients', 'cmocean', nutrientPalettes);

fprintf('Created:\n');
for outputIndex = 1:numel(outputFiles)
    fprintf('  %s\n', outputFiles{outputIndex});
end
end

function buildMatrix(inputDir, outputFile, columns, variableIds, rowLabels, ...
    workflow, paletteMode, paletteNames)
panelFiles = cell(numel(variableIds), numel(columns));
missingFiles = {};

for row = 1:numel(variableIds)
    for col = 1:numel(columns)
        panelName = sprintf('%s_%s_%s.png', columns(col).season, ...
            columns(col).station, variableIds{row});
        panelFiles{row, col} = fullfile(inputDir, panelName);
        if ~isfile(panelFiles{row, col})
            missingFiles{end + 1} = panelName; %#ok<AGROW>
        end
    end
end

if ~isempty(missingFiles)
    error(['Cannot assemble %s matrix. Run the corresponding Live Scripts ', ...
        'first. Missing files:\n  %s'], workflow, strjoin(missingFiles, '\n  '));
end

fig = figure( ...
    'Visible', 'off', ...
    'Color', 'white', ...
    'Units', 'inches', ...
    'Position', [1, 1, 20, 20]);
cleanup = onCleanup(@() close(fig));

left = 0.065;
right = 0.040;
groupGap = 0.030;
columnGap = 0.010;
colorbarGap = 0.008;
colorbarWidth = 0.050;
plotHeight = 0.090;
rowStep = 0.137;
firstRowY = 0.735;
groupHeaderY = 0.900;
seasonHeaderY = 0.865;

availableWidth = 1 - left - right - groupGap - 5 * columnGap ...
    - colorbarGap - colorbarWidth;
plotWidth = availableWidth / 6;

panelNumber = 1;
for row = 1:numel(variableIds)
    rowY = firstRowY - (row - 1) * rowStep;
    rowImages = cell(1, numel(columns));
    rowBounds = cell(1, numel(columns));
    if strcmp(paletteMode, 'cmocean')
        targetMap = cmocean(paletteNames{row}, 256);
    else
        targetMap = [];
    end

    for col = 1:numel(columns)
        rowImages{col} = readRgb(panelFiles{row, col});
        rowBounds{col} = findMainPlot(rowImages{col});

        x = left + (col - 1) * (plotWidth + columnGap);
        if col > 3
            x = x + groupGap;
        end

        bounds = rowBounds{col};
        plotImage = rowImages{col}(bounds(2):bounds(4), ...
            bounds(1):bounds(3), :);
        if strcmp(paletteMode, 'cmocean')
            plotImage = remapJetColours(plotImage, targetMap);
        end
        imageAxes(fig, [x, rowY, plotWidth, plotHeight], plotImage);

        addLabel(fig, [x, rowY + plotHeight + 0.001, plotWidth, 0.012], ...
            sprintf('(%d)', panelNumber), 12, 'normal');
        panelNumber = panelNumber + 1;

        if row == numel(variableIds)
            addDayTicks(fig, x, rowY, plotWidth, workflow, ...
                columns(col).station);
        end
        if col == 1 || col == 4
            addDepthTicks(fig, x, rowY, plotHeight, columns(col).station);
        end
    end

    addLabel(fig, [0.24, rowY + plotHeight + 0.017, 0.52, 0.022], ...
        rowLabels{row}, 18, 'bold');

    [barImage, found] = extractColorbar(rowImages{end}, rowBounds{end});
    if found
        if strcmp(paletteMode, 'cmocean')
            barImage = remapJetColours(barImage, targetMap);
        end
        barX = 1 - right - colorbarWidth;
        imageAxes(fig, [barX, rowY - 0.008, colorbarWidth, ...
            plotHeight + 0.016], barImage);
    else
        warning('Color bar could not be detected for %s.', variableIds{row});
    end
end

addLabel(fig, [left, groupHeaderY, 3 * plotWidth + 2 * columnGap, 0.030], ...
    'Offshore', 25, 'bold');
coastX = left + 3 * (plotWidth + columnGap) + groupGap;
addLabel(fig, [coastX, groupHeaderY, 3 * plotWidth + 2 * columnGap, 0.030], ...
    'Coast', 25, 'bold');

for col = 1:numel(columns)
    x = left + (col - 1) * (plotWidth + columnGap);
    if col > 3
        x = x + groupGap;
    end
    addLabel(fig, [x, seasonHeaderY, plotWidth, 0.025], columns(col).season, ...
        18, 'bold');
end

addSharedAxisLabels(fig);

exportgraphics(fig, outputFile, ...
    'Resolution', 300, ...
    'BackgroundColor', 'white');
clear cleanup
end

function recoloured = remapJetColours(rgb, targetMap)
% Preserve text and grey sampling marks while replacing rasterised jet data.
sourceMap = jet(size(targetMap, 1));
flatRgb = reshape(rgb, [], 3);
flatUnit = numericToUnitDouble(flatRgb);
chroma = max(flatUnit, [], 2) - min(flatUnit, [], 2);
candidateIndices = find(chroma > 0.035);

if isempty(candidateIndices)
    recoloured = rgb;
    return
end

candidateColours = flatUnit(candidateIndices, :);
[uniqueColours, ~, membership] = unique(candidateColours, 'rows');
replacementColours = uniqueColours;
maximumDistanceSquared = 0.025 ^ 2;
chunkSize = 20000;

sourceNormSquared = sum(sourceMap .^ 2, 2).';
for first = 1:chunkSize:size(uniqueColours, 1)
    last = min(size(uniqueColours, 1), first + chunkSize - 1);
    chunk = uniqueColours(first:last, :);
    distances = sum(chunk .^ 2, 2) + sourceNormSquared ...
        - 2 * (chunk * sourceMap.');
    [nearestDistance, nearestIndex] = min(distances, [], 2);
    matched = nearestDistance <= maximumDistanceSquared;
    chunkReplacement = chunk;
    chunkReplacement(matched, :) = targetMap(nearestIndex(matched), :);
    replacementColours(first:last, :) = chunkReplacement;
end

flatUnit(candidateIndices, :) = replacementColours(membership, :);
recoloured = uint8(round(reshape(flatUnit, size(rgb)) * 255));
end

function rgb = readRgb(fileName)
[imageData, colorMap, alpha] = imread(fileName);

if ~isempty(colorMap)
    rgb = uint8(round(ind2rgb(imageData, colorMap) * 255));
elseif ismatrix(imageData)
    rgb = repmat(imageData, 1, 1, 3);
else
    rgb = imageData(:, :, 1:3);
end

if ~isempty(alpha)
    alphaDouble = numericToUnitDouble(alpha);
    rgbDouble = numericToUnitDouble(rgb);
    rgbDouble = rgbDouble .* alphaDouble + (1 - alphaDouble);
    rgb = uint8(round(rgbDouble * 255));
end
end

function bounds = findMainPlot(rgb)
unitRgb = numericToUnitDouble(rgb);
chroma = max(unitRgb, [], 3) - min(unitRgb, [], 3);
colored = chroma > 0.035;

rowCandidates = mean(colored, 2) > 0.35;
[top, bottom] = widestRun(rowCandidates);
if isempty(top)
    error('Could not detect the coloured plot area in an input panel.');
end

columnCandidates = mean(colored(top:bottom, :), 1) > 0.35;
% Grey sampling profiles can split the coloured field into narrow strips.
% Join only short gaps; the larger white gap before the color bar remains.
columnCandidates = fillShortGaps(columnCandidates, ...
    round(size(rgb, 2) * 0.015));
[left, right] = widestRun(columnCandidates);
if isempty(left)
    error('Could not detect the main plot columns in an input panel.');
end

bounds = [left, top, right, bottom];
end

function [barImage, found] = extractColorbar(rgb, plotBounds)
unitRgb = numericToUnitDouble(rgb);
chroma = max(unitRgb, [], 3) - min(unitRgb, [], 3);
colored = chroma > 0.035;

searchLeft = plotBounds(3) + 1;
if searchLeft > size(rgb, 2)
    barImage = [];
    found = false;
    return
end

top = plotBounds(2);
bottom = plotBounds(4);
columnCandidates = mean(colored(top:bottom, searchLeft:end), 1) > 0.35;
[relativeLeft, relativeRight] = widestRun(columnCandidates);
if isempty(relativeLeft)
    barImage = [];
    found = false;
    return
end

barLeft = searchLeft + relativeLeft - 1;
barRight = searchLeft + relativeRight - 1;
tickPadding = round(size(rgb, 2) * 0.110);
cropRight = min(size(rgb, 2), barRight + tickPadding);
verticalPadding = round((bottom - top + 1) * 0.085);
cropTop = max(1, top - verticalPadding);
cropBottom = min(size(rgb, 1), bottom + verticalPadding);
barImage = rgb(cropTop:cropBottom, barLeft:cropRight, :);
found = true;
end

function imageAxes(fig, position, imageData)
ax = axes(fig, 'Units', 'normalized', 'Position', position, ...
    'Visible', 'off');
image(ax, imageData);
set(ax, ...
    'Visible', 'off', ...
    'XLim', [0.5, size(imageData, 2) + 0.5], ...
    'YLim', [0.5, size(imageData, 1) + 0.5], ...
    'YDir', 'reverse');
end

function addDayTicks(fig, x, y, width, workflow, station)
if strcmp(workflow, 'nutrients') && strcmp(station, 'S6')
    dayCount = 7;
else
    dayCount = 8;
end

for day = 1:dayCount
    edgeInset = 0.035;
    fraction = edgeInset + (1 - 2 * edgeInset) * ...
        (day - 1) / (dayCount - 1);
    labelWidth = 0.014;
    tickX = x + fraction * width - labelWidth / 2;
    addLabel(fig, [tickX, y - 0.030, labelWidth, 0.025], ...
        sprintf('%02d', day), 9, 'normal', 45);
end
end

function addSharedAxisLabels(fig)
overlay = axes(fig, ...
    'Units', 'normalized', ...
    'Position', [0, 0, 1, 1], ...
    'Color', 'none', ...
    'Visible', 'off', ...
    'XLim', [0, 1], ...
    'YLim', [0, 1]);

text(overlay, 0.020, 0.48, 'Depth (m)', ...
    'Units', 'normalized', ...
    'Interpreter', 'tex', ...
    'FontName', 'Arial', ...
    'FontSize', 19, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', ...
    'Rotation', 90);
text(overlay, 0.50, 0.135, 'Time (days)', ...
    'Units', 'normalized', ...
    'Interpreter', 'tex', ...
    'FontName', 'Arial', ...
    'FontSize', 19, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle');
end

function addDepthTicks(fig, x, y, height, station)
if strcmp(station, 'S3')
    labels = {'-50', '-100', '-150'};
    fractions = [0.25, 0.50, 0.75];
else
    labels = {'-20', '-40', '-60'};
    fractions = [20, 40, 60] / 70;
end

for index = 1:numel(labels)
    tickY = y + height * (1 - fractions(index)) - 0.009;
    addLabel(fig, [x - 0.040, tickY, 0.035, 0.018], ...
        labels{index}, 10, 'normal');
end
end

function addLabel(fig, position, label, fontSize, fontWeight, rotation)
if nargin < 6
    rotation = 0;
end
annotation(fig, 'textbox', position, ...
    'String', label, ...
    'Interpreter', 'tex', ...
    'FontName', 'Arial', ...
    'FontSize', fontSize, ...
    'FontWeight', fontWeight, ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', ...
    'Rotation', rotation, ...
    'EdgeColor', 'none', ...
    'Margin', 0);
end

function [first, last] = widestRun(logicalVector)
logicalVector = logical(logicalVector(:).');
edges = diff([false, logicalVector, false]);
starts = find(edges == 1);
ends = find(edges == -1) - 1;

if isempty(starts)
    first = [];
    last = [];
    return
end

[~, widest] = max(ends - starts + 1);
first = starts(widest);
last = ends(widest);
end

function logicalVector = fillShortGaps(logicalVector, maximumGap)
logicalVector = logical(logicalVector(:).');
edges = diff([true, logicalVector, true]);
starts = find(edges == -1);
ends = find(edges == 1) - 1;

for gap = 1:numel(starts)
    if ends(gap) - starts(gap) + 1 <= maximumGap
        logicalVector(starts(gap):ends(gap)) = true;
    end
end
end

function values = numericToUnitDouble(values)
if isinteger(values)
    values = double(values) / double(intmax(class(values)));
else
    values = double(values);
end
end
