function outputFiles = generate_longitudinal_sections(outputDir)
%GENERATE_LONGITUDINAL_SECTIONS Rebuild the ENV1-ENV3 vertical sections.
%   GENERATE_LONGITUDINAL_SECTIONS reads the six curated workbooks in
%   data/longitudinal and generates CTD and nutrient sections for winter,
%   spring, and summer. Both the historical jet rendering and a
%   variable-appropriate cmocean rendering are written by default.
%
%   OUTPUTFILES = GENERATE_LONGITUDINAL_SECTIONS(OUTPUTDIR) writes the
%   generated panels below a custom directory and returns their paths.

scriptDir = fileparts(mfilename('fullpath'));
repoRoot = fileparts(fileparts(scriptDir));
dataDir = fullfile(repoRoot, 'data', 'longitudinal');

if nargin < 1 || isempty(outputDir)
    outputDir = fullfile(repoRoot, 'figures', 'longitudinal');
end

if ~isfolder(dataDir)
    error('Longitudinal input directory not found: %s', dataDir);
end

addpath(fullfile(repoRoot, 'third_party'));

surveys = struct( ...
    'season', {'winter', 'spring', 'summer'}, ...
    'label', {'Winter', 'Spring', 'Summer'}, ...
    'ctdFile', {'ctd_env1_d7.xlsx', 'ctd_env2_d7.xlsx', ...
        'ctd_env3_d5.xlsx'}, ...
    'nutrientFile', {'nuts_env1_d1.xlsx', 'nuts_env2_d1.xlsx', ...
        'nuts_env3_d1.xlsx'});

ctdVariables = [ ...
    sectionVariable('temperature', 'temp', 'Temperature (^{\circ}C)', ...
        [12, 16], 'thermal'), ...
    sectionVariable('salinity', 'sal', 'Salinity (PSU)', ...
        [34, 36], 'haline'), ...
    sectionVariable('fluorescence', 'fluo', ...
        'Fluorescence (\mug L^{-1})', [-0.11, 10], 'algae'), ...
    sectionVariable('turbidity', 'turb', 'Turbidity (NTU)', ...
        [-0.09, 4], 'turbid'), ...
    sectionVariable('par', 'par', ...
        'PAR (\mumol photons m^{-2} s^{-1})', [0.0001, 100], 'solar')];

nutrientVariables = [ ...
    sectionVariable('no2', 'no2', 'NO_{2}^{-} (\mumol L^{-1})', ...
        [0, 0.5], 'matter'), ...
    sectionVariable('no3', 'no3', 'NO_{3}^{-} (\mumol L^{-1})', ...
        [0, 10], 'matter'), ...
    sectionVariable('nh4', 'nh4', 'NH_{4}^{+} (\mumol L^{-1})', ...
        [0, 0.8], 'matter'), ...
    sectionVariable('tin', 'TIN', 'TIN (\mumol L^{-1})', ...
        [0, 10], 'matter'), ...
    sectionVariable('po4', 'po4', 'PO_{4}^{3-} (\mumol L^{-1})', ...
        [0.1, 0.8], 'matter'), ...
    sectionVariable('sio2', 'sio2', 'SiO_{2} (\mumol L^{-1})', ...
        [4, 8], 'matter'), ...
    sectionVariable('chlorophyll_a', 'Total_Chla', ...
        'Chl-a (mg m^{-3})', [0, 10], 'algae')];

paletteModes = {'original', 'cmocean'};
outputFiles = {};

for modeIndex = 1:numel(paletteModes)
    paletteMode = paletteModes{modeIndex};
    modeOutputDir = fullfile(outputDir, paletteMode);
    if ~isfolder(modeOutputDir)
        mkdir(modeOutputDir);
    end

    for surveyIndex = 1:numel(surveys)
        survey = surveys(surveyIndex);

        ctd = readtable(fullfile(dataDir, survey.ctdFile), ...
            'VariableNamingRule', 'preserve');
        validateColumns(ctd, [{'Longitude', 'depth'}, ...
            {ctdVariables.column}]);
        ctdOutputs = generateVariableSet(ctd, 'Longitude', 'depth', ...
            ctdVariables, survey, paletteMode, modeOutputDir, 260);

        nutrients = readtable(fullfile(dataDir, survey.nutrientFile), ...
            'VariableNamingRule', 'preserve');
        validateColumns(nutrients, [{'lon', 'Prof'}, ...
            {nutrientVariables.column}]);
        nutrientOutputs = generateVariableSet(nutrients, 'lon', 'Prof', ...
            nutrientVariables, survey, paletteMode, modeOutputDir, 200);

        outputFiles = [outputFiles, ctdOutputs, nutrientOutputs]; %#ok<AGROW>
    end
end

fprintf('Created %d longitudinal panels below:\n  %s\n', ...
    numel(outputFiles), outputDir);
end

function variable = sectionVariable(id, column, label, limits, palette)
variable = struct( ...
    'id', id, ...
    'column', column, ...
    'label', label, ...
    'limits', limits, ...
    'palette', palette);
end

function outputFiles = generateVariableSet(data, longitudeColumn, ...
    depthColumn, variables, survey, paletteMode, outputDir, depthLimit)
longitude = data.(longitudeColumn);
depth = data.(depthColumn);
outputFiles = cell(1, numel(variables));

for variableIndex = 1:numel(variables)
    variable = variables(variableIndex);
    values = data.(variable.column);
    valid = isfinite(longitude) & isfinite(depth) & isfinite(values) ...
        & depth >= 0 & depth <= depthLimit;

    if nnz(valid) < 3
        error('Not enough finite observations for %s in %s.', ...
            variable.column, survey.label);
    end

    figureHandle = createSectionFigure(longitude(valid), depth(valid), ...
        values(valid), variable, survey.label, paletteMode, depthLimit);
    cleanup = onCleanup(@() close(figureHandle));

    fileName = sprintf('%s_%s.png', survey.season, variable.id);
    outputFiles{variableIndex} = fullfile(outputDir, fileName);
    exportgraphics(figureHandle, outputFiles{variableIndex}, ...
        'Resolution', 300, 'BackgroundColor', 'white');
    clear cleanup
end
end

function figureHandle = createSectionFigure(longitude, depth, values, ...
    variable, seasonLabel, paletteMode, depthLimit)
longitudeGrid = linspace(min(longitude), max(longitude), 60);
depthGrid = (5:5:depthLimit).';
[queryLongitude, queryDepth] = meshgrid(longitudeGrid, depthGrid);
interpolated = griddata(longitude, depth, values, ...
    queryLongitude, queryDepth, 'linear');

figureHandle = figure( ...
    'Visible', 'off', ...
    'Color', 'white', ...
    'Units', 'inches', ...
    'Position', [1, 1, 8.5, 5.2]);
axesHandle = axes(figureHandle);

surface(axesHandle, queryLongitude, -queryDepth, ...
    zeros(size(interpolated)), interpolated, ...
    'EdgeColor', 'none', ...
    'FaceColor', 'interp');
view(axesHandle, 2);
hold(axesHandle, 'on');
scatter(axesHandle, longitude, -depth, 12, 'o', ...
    'MarkerFaceColor', 'none', ...
    'MarkerEdgeColor', [0.35, 0.35, 0.35], ...
    'LineWidth', 0.6);

if strcmp(paletteMode, 'cmocean')
    colormap(axesHandle, cmocean(variable.palette, 256));
else
    colormap(axesHandle, jet(256));
end
clim(axesHandle, variable.limits);
colorbar(axesHandle);

xlim(axesHandle, [min(longitude), max(longitude)]);
ylim(axesHandle, [-depthLimit, 0]);
xticks(axesHandle, [8.956, 9.608]);
xticklabels(axesHandle, {'Coast', 'Offshore'});
depthTicks = 0:50:depthLimit;
yticks(axesHandle, -fliplr(depthTicks));
yticklabels(axesHandle, string(fliplr(depthTicks)));

xlabel(axesHandle, 'Transect position');
ylabel(axesHandle, 'Depth (m)');
title(axesHandle, sprintf('%s - %s', seasonLabel, variable.label), ...
    'Interpreter', 'tex');
set(axesHandle, ...
    'FontName', 'Arial', ...
    'FontSize', 12, ...
    'TickDir', 'out', ...
    'Layer', 'top', ...
    'Box', 'on');
end

function validateColumns(data, requiredColumns)
missing = setdiff(requiredColumns, data.Properties.VariableNames, 'stable');
if ~isempty(missing)
    error('Required workbook columns are missing: %s', ...
        strjoin(missing, ', '));
end
end
